replicaCount: 2
image:
  repository: nadra187/guess-game-test
  tag: "1.0"
  pullPolicy: IfNotPresent
appMessage: "Hello from Day1 App!"
service:
  name: load-balancer-service
  type: LoadBalancer
  port: 8080
  targetPort: 8080